### PR TITLE
fix path issue , if path not exist

### PR DESCRIPTION
**Pull request by shawon1fb**

### CODE REVIEW

**Comment by daison12006013** [comment]
Hi @shawon1fb, can you rebase your develop branch from my latest develop branch please

**Comment by shawon1fb** [comment]
@daison12006013 can you please set develop as the default branch. Most of the time I forgot to change branch and its also helpful to update with one click

**Comment by shawon1fb** [comment]
@daison12006013 you might enable the discussion section from settings for general queries.

**Comment by daison12006013** [comment]
Hi @shawon1fb, changed the default branch into develop, also enabled discussion

**Comment by shawon1fb** [comment]
@daison12006013   I updated my branch.  I think this request is ok with no conflict ...

**Pull request merged**
